version: "3"
# run from terminal like:
# apikey=xxx run_max_hours=z docker-compose up
# replace xxx with your valid apikey
# or
# replace xxx with DUMMY to use only fabricated fake + possible old valid data in the DB.
# apikey=DUMMY enables running the application without loading the external apilayer.com web site.
# With DUMMY (or other invalid) apikey the process is seen to repeat every hour, but
# no new data is received. Fake (+ possible valid old data) rows in the DB table is anyway
# shown at every round. With DUMMY no query is sent to avoid unnecessary load to the external 
# apilayer.com forex data web site. With any other invalid apikey the query is sent but error message
# is received from the external API - ignored - no new data is stored.
# Replace z by number of hours to run [-1,0,1,...]:
# run_max_hours=-1 -> run queries once immediately and repeat at each full hour forever.
# run_max_hours=0  -> run queries only just once immediately, never repeat.
# run_max_hours=1  -> run queries once immediately and repeat only once at the next full hour.
# ...
# run_max_hours=7  -> run queries once immediately and repeat at every next full hour 7 times.   
# restart: [always, unless-stopped, on-failure, "no"]
# restart: "no" with quotes because in yaml no is interpreted as false!
# depends_on forex_db means spin up after forex_db is running
services:
    forex_to_db:
      image: 'forex_to_db:latest'
      build: .
      container_name: forex_to_db
      
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://forex_db:5432/forex_db
        apikey: ${apikey}
        run_max_hours: ${run_max_hours} 
      
      ports:
        - 8080:8080
      restart: "no"
      depends_on:
        - forex_db

# browser UI to the posgreSQL DB (not necessary)
# https://youtu.be/nlk0QlPdbcY

    adminer:
      image: adminer
      container_name: adminer
      environment:
        - POSTGRES_USER=postgres
      ports:
        - 8007:8080
      restart: "no"
      depends_on:
      - forex_db

    forex_db:
      image: postgres
      container_name: forex_db
      env_file: db.conf
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=forex_db
        - FOREX_DATA=/var/lib/postgresql/data/forex_data

      ports:
        - "5432:5432"
      expose:
      - "5432" 
      volumes:
        - forex_vol:/var/lib/postgresql/data
      restart: unless-stopped
volumes:
    forex_vol:
